### ISSUE TITLE
zTree 3.5.19

### ISSUE THREAD

**Issue by Stephan972** [webjars/zTree#1]
Hi,

There's a new version for zTree: 3.5.19.

How can it be added to Webjars?

Thanks.

Github: https://github.com/zTree/zTree_v3/

**Comment by jamesward** [comment]
I don't see that release tagged: https://github.com/zTree/zTree_v3/releases

Is there another download URL that has that release?

**Comment by Stephan972** [comment]
On the official website, the latest releases can be downloaded here: https://git.oschina.net/zTree/zTree_v3/repository/archive/master

@jamesward , Do you think it's possible to fill automatically the gap between 3.5.15 and 3.5.20 on Webjars?

**Comment by jamesward** [comment]
We need upstream tagged / immutable releases for WebJar releases.  So you'll need to work with the upstream project to create a tag or publish a release somewhere.  In the meantime I can add releases for `3.5.16`, `3.5.17`, and `3.5.18` if you need them.

**Comment by Stephan972** [comment]
It's ok if you can add `3.5.16`, `3.5.17` and `3.5.18`.

**Comment by Stephan972** [comment]
Thank you James ;)
