### ISSUE TITLE
Please Release Version: 3.5.42

### ISSUE THREAD

**Issue by linghengqian** [webjars/zTree#4]
The Lalast verson is 3.5.46 in https://github.com/zTree/zTree_v3.Thank you for your attention to this javascript component.

**Comment by jamesward** [comment]
The newest release I see there is `3.5.42` - let me know if you want that one.

**Comment by linghengqian** [comment]
Sorry, the latest version is really 3.5.42, I read the wrong version number earlier. Can you post 3.5.42? ZTree 3.5.37, which is currently attached to Webjars.org, relies on a version of Jquery that is not up to date and can sometimes confuse developers.
